name: FlavorMate Android workflow
on:
  push:
    tags: [ v* ]

env:
  FLUTTER_VERSION: 3.35.7

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      
      # Setting up android signing
      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: dart run build_runner build -d

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle --release

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
          working-directory: android/
      
      - name: Install ruby dependencies
        working-directory: android/
        run: bundle install

      - name: Deploy to Google Play Console
        working-directory: android/
        run: fastlane deployGooglePlayConsole
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.ANDROID_CONSOLE_JSON }}

      - name: Delete Android keys
        if: always()  # Ensure this runs regardless of job success or failure
        run: |
          rm -f android/app/keystore.jks
          rm -f android/key.properties
