name: FlavorMate build workflow
on:
  push:
    tags: [ v* ]

env:
  FLUTTER_VERSION: 3.35.7
  RUBY_VERSION: 3.4
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/flavormate-webapp

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      
      # Setting up android signing
      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: dart run build_runner build -d

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle --release

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: android/
      
      - name: Install ruby dependencies
        working-directory: android/
        run: bundle install

      - name: Deploy to Google Play Console
        working-directory: android/
        run: fastlane deployGooglePlayConsole
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.ANDROID_CONSOLE_JSON }}
      
      - name: Cache Android Files
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: flavormate-android
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          retention-days: 1

      - name: Delete Android keys
        if: always()  # Ensure this runs regardless of job success or failure
        run: |
          rm -f android/keystore.jks
          rm -f android/key.properties

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: dart run build_runner build -d

      - name: Generate Flutter configs
        run: flutter build ios --config-only

      - name: Install ruby dependencies
        working-directory: ios/
        run: bundle install

      - name: Build and deploy to Testflight
        working-directory: ios/
        run: bundle exec fastlane deployTestflight
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: dart run build_runner build -d
        
      - name: Install Pods
        working-directory: macos/
        run: pod install
      
      - name: Generate Flutter configs
        run: flutter build macos --config-only

      - name: Install ruby dependencies
        working-directory: macos/
        run: bundle install

      - name: Build and deploy to Testflight
        working-directory: macos/
        run: bundle exec fastlane deployTestflight
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}

      - name: Build notarized application
        working-directory: macos/
        run: bundle exec fastlane buildAndNotarizeApp
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      
      - name: Cache macOS File
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: flavormate-macos
          path: |
            macos/build/notarized_app/FlavorMate.app.zip
          retention-days: 1

  build-webapp:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: dart run build_runner build -d

      - name: Build Web
        run: flutter build web --wasm --release

      - name: Prepare web archive
        run: |
          cd build/web
          # modifying service worker to exclude the backend url file from getting cached
          sed -i '/"assets\/assets\/web\/backend_url.txt"/d' flutter_service_worker.js

      - name: Create web archive
        run: |
          cd build
          tar -czf web_build.tar.gz web

      - name: Cache web File
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: flavormate-web
          path: |
            build/web_build.tar.gz
          retention-days: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build_assets/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Remove untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
          token: ${{ secrets.GITHUB_TOKEN }}
          package: flavormate-webapp

  create-release:
    needs:
      - build-android
      - build-ios
      - build-macos
      - build-webapp

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download web archive
        uses: actions/download-artifact@v4
        with:
          name: flavormate-web
          path: build

      - name: Download macos archive
        uses: actions/download-artifact@v4
        with:
          name: flavormate-macos
          path: build

      - name: Download android archive
        uses: actions/download-artifact@v4
        with:
          name: flavormate-android
          path: build

      - name: List files
        working-directory: build
        run: ls -la

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/flutter-apk/app-release.apk,build/bundle/release/app-release.aab,build/FlavorMate.app.zip,build/web_build.tar.gz"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          removeArtifacts: true
          replacesArtifacts: true


